#!/bin/sh
# ------------------------------------------------------------------------
# inst-kernel v0.6 - 2003/01/13 - Willy Tarreau - willy@ant-computing.com
# ------------------------------------------------------------------------
# This script installs and packages the kernel compiled in the current dir
# nto /tmp/build-$$.
# The name of the configuration files specify the architecture, and final
# repository :
#   - config-.*-i586mmx will result in "kernel-xxx-i586mmx"
#   - config-.*smp-i686 will result in "kernel-xxx-smp-i686", and the
#     "smp" suffix to be appended to EXTRAVERSION.
#
# don't forget to run as root if you want to build standard packages !
#

TMPDIR=/tmp/willy/build-$$
CC=gcc
PARALLELDEP=20
PARALLELCC=4

if [ $# -lt 1 ]; then
   echo "Usage: $0 [ -v <extraversion> ] [ -b <build_version> ] arch_name"
   exit 1
fi

eval `grep EXTRAVERSION.*= Makefile|tr -d ' \011'`
VERSIONRADIX=$EXTRAVERSION
if [ "$1" = "-v" ]; then
    VERSIONRADIX="$2"
    shift 2
fi

if [ "$1" = "-b" ]; then
    BUILDVERSION="$2"
    shift 2
fi

mkdir -p $TMPDIR

basearch=$1
if grep -q '^CONFIG_SMP=y' .config; then
    arch=smp-$basearch
    EXTRAVERSION=${VERSIONRADIX}-smp
else
    EXTRAVERSION=${VERSIONRADIX}
    arch=$basearch
fi
export EXTRAVERSION

destdir=$TMPDIR/$arch
echo $arch
rm -rf $destdir/lib $destdir/boot

( make modules_install EXTRAVERSION=$EXTRAVERSION INSTALL_MOD_PATH=$destdir HOSTCC=$CC CC=$CC && \
     cp arch/i386/boot/bzImage .config System.map $destdir/lib/modules/* )

if [ $? -ne 0 -o "`echo $destdir/lib/modules/*.*.*`" = "$destdir/lib/modules/*.*.*" ]; then
    	echo "$arch failed"
	continue
fi

(cd $destdir/lib/modules ;
 VERSION=`echo *.*.*`
 cp $VERSION/.config $TMPDIR/config-${VERSION}${BUILDVERSION}-$basearch
 gzip -9 $VERSION/.config
 rm -f $VERSION/build
 for i in `find . -type f -name '*.o'`; do
   echo "Compressing $i -> $i.gz"
   strip -S $i && gzip -c9 < $i > $i.gz && mv $i.gz $i
 done
 ln -s $VERSION/System.map System.map-$VERSION
 cd ../.. ; mv lib/modules boot ; rmdir lib
 echo "Archiving package..."
 find boot -xdev \( -not -type d -o -empty \) | tar -T - -vcf - \
   |gzip -9 >$TMPDIR/kernel-${VERSION}${BUILDVERSION}-$basearch.tar.gz
 signfs `find boot -xdev \( -not -type d -o -empty \)` >$TMPDIR/kernel-${VERSION}${BUILDVERSION}-$basearch.lst
 echo "$arch installed"
)

echo "Kernel installed in $TMPDIR"

