#!/bin/bash
#
# pkg-filter - Formilux Package Filter - version 0.1.0 - 2012-05-03
#
# Copyright (C) 2001-2012 Benoit Dolez, Willy Tarreau
# Copyright (C) 2011-2012 Emeric Brun
#
# This program is licenced under GPLv2 ( http://www.gnu.org/licenses/gpl.txt )
#
# Usage:
#   pkg-filter <action>
#


[ -n "$PKGFILTEREDDIR" ] || { echo "Please specify PKGFILTEREDDIR" ;  exit 1 ; }
[ -n "$PRJ_DIR" ] || { echo "env PRJ_DIR is not set" >&2 ; exit 1 ; }

function do_update() {
	local repo
	local newpackages
	local new
	local package

	if [ -z "$TMP_PACK" ]; then
		echo "TMP_PACK is not set, it should probably point to build/\$MODEL/packaging."
		echo "pkg-filter update is normally not supposed to be manually called."
		exit 1
	fi

	mkdir -p $PKGFILTEREDDIR/
	[ $? -eq 0 ] || { echo "Unable to create $PKGFILTEREDDIR" >&2 ; exit 1 ; }

	rm -f $PKGFILTEREDDIR/*

	if [ -f "$PRJ_DIR/packaging/bld/formilux.bld" ]; then
		${FLXTECHNO}/scripts/env-expand "$PRJ_DIR/packaging/lpk/"*.lpk > ${TMP_PACK}/allbuild.lpk
		echo -n "Preparing $PKGFILTEREDDIR from formilux.bld..."
		while read package trash ; do
			if [ -d "$DEVROOT/$package" ] ; then
				ln -s "$DEVROOT/$package" "$PKGFILTEREDDIR/" || echo " Maybe package $package appears twice ?" >&2
				[ ! -d "$PKGROOT/$package" ] || { echo " error" ; echo "Error package $package is both in DEVROOT and PKGROOT, please fix conflict" >&2 ; exit 1 ; }
			elif [ -d "$PKGROOT/$package" ] ; then
				ln -s "$PKGROOT/$package" "$PKGFILTEREDDIR/" || echo " Maybe package $package appears twice ?" >&2
			else
				echo " error"
				echo "Error $package not found, your cache may not up to date try: ( pkg-cache update )" >&2
				exit 1
			fi
			echo -n "."
		done < "$PRJ_DIR/packaging/bld/formilux.bld"
		echo " success"
	else
		echo -n "Preparing $PKGFILTEREDDIR from *.lpk..."

		${FLXTECHNO}/scripts/env-expand "$PRJ_DIR/packaging/lpk/"*.lpk | \
		    tee ${TMP_PACK}/allbuild.lpk | while read package archs rest ; do
			if [ -n "${archs}" -a -z "${archs##build:*}" ]; then
				continue
			fi

			# Note: we might have a model name in sfxver after an underscore
			p=${package##*-flx}
			if [ "${p/_/}" != "$p" ] ; then
				package=${package%_*}
			fi

			if [ -d "$DEVROOT/$package" ] ; then
				ln -s "$DEVROOT/$package" "$PKGFILTEREDDIR/" || echo " Maybe package $package appears twice ?" >&2
				[ ! -d "$PKGROOT/$package" ] || { echo " error" ; echo "Error package $package is both in DEVROOT and PKGROOT, please fix conflict" >&2 ; exit 1 ; }
			elif [ -d "$PKGROOT/$package" ] ; then
				ln -s "$PKGROOT/$package" "$PKGFILTEREDDIR/" || echo " Maybe package $package appears twice ?" >&2
			else
				echo " error"
				echo "Error $package not found, your cache may not up to date try: ( pkg-cache update )" >&2
				exit 1
			fi
			echo -n "."
		done || exit $?
		echo " success"
	fi

	echo -n "Filter components "
	find "${COMP_DIR:-$PRJ_DIR/components}/pkg/" -type f  -name 'Version' | while read package trash ; do
		version=$( cat $package )
		package="${package%/*}"
		ln -s $package $PKGFILTEREDDIR/$version
		[ $? -ne 0 ] && { echo " error"; echo "Error create link on component ${package##*/}" >&2 ; exit 1 ; }
		echo -n "."
	done
	echo " success"
}

function do_flush() {
	mkdir -p $PKGFILTEREDDIR/
        [ $? -eq 0 ] || { echo "Unable to create $PKGFILTEREDDIR" >&2 ; exit 1 ; }

        rm -f $PKGFILTEREDDIR/*
}

function do_cleanall() {
	mkdir -p $PKGFILTEREDDIR/
        [ $? -eq 0 ] || { echo "Unable to create $PKGFILTEREDDIR" >&2 ; exit 1 ; }

        rm -fv $PKGFILTEREDDIR/*-*-flx*\.*/compiled/*.tgz
        rm -f $PKGFILTEREDDIR/*-*-flx*\.*/compiled/*.lst
        rm -f $PKGFILTEREDDIR/*-*-flx*\.*/compiled/*.dep
}

function do_cleancomponents() {
	mkdir -p $PKGFILTEREDDIR/
        [ $? -eq 0 ] || { echo "Unable to create $PKGFILTEREDDIR" >&2 ; exit 1 ; }

        rm -fv $PKGFILTEREDDIR/*-0local-flx2\.1/compiled/*.tgz
        rm -f $PKGFILTEREDDIR/*-0local-flx2\.1/compiled/*.lst
        rm -f $PKGFILTEREDDIR/*-0local-flx2\.1/compiled/*.dep
}


function do_clean() {
	mkdir -p $PKGFILTEREDDIR/
        [ $? -eq 0 ] || { echo "Unable to create $PKGFILTEREDDIR" >&2 ; exit 1 ; }
	while [ $# -gt 0 ] ; do
		rm -fv $PKGFILTEREDDIR/$1-*-flx*\.*/compiled/*.tgz
		rm -f $PKGFILTEREDDIR/$1-*-flx*\.*/compiled/*.lst
		rm -f $PKGFILTEREDDIR/$1-*-flx*\.*/compiled/*.dep
		shift;
	done
}

function do_list() {
        mkdir -p $PKGFILTEREDDIR/
        [ $? -eq 0 ] || { echo "Unable to create $PKGFILTEREDDIR" >&2 ; exit 1 ; }
	find  $PKGFILTEREDDIR -xtype d -name '*-*-flx*.*' -printf '%P\n'
}

function do_archive() {
	if [ -z "$1" ]; then
		echo "Missing output archive name"
		exit 1
	fi
	(cd "$PKGFILTEREDDIR" && tar --exclude='compiled/*' --exclude='.svn' -cf - */* | gzip -nc9) > "$1"
}

case $1 in
	update)
		do_update
		;;
	cleanall)
		do_cleanall
		;;
	cleancomponents)
		do_cleancomponents
		;;
	clean)
		shift;
		do_clean "$@"
		;;
	flush)
		do_flush
		;;
	list)
		do_list
		;;
	archive)
		shift;
		do_archive "$@"
		;;
	*)
		echo "pkgfilter <command>"
		echo "    update: look for packages in PKGROOT and PKGDEV, and create corresponding links into PKGFILTEREDDIR"
		echo "    list: list fitered packages"
		echo "    cleanall: remove all binaries in filtered"
		echo "    cleancomponents: remove all binaries only in components"
		echo "    clean <name> ..: remove all binaries for package <name>-*-flx*.*"
		echo "    archive <file> : make a tar.gz archive of all filtered packages without binaries"
esac

