#!/bin/bash
# uClibc wrapper v0.7 - 2013/10/28 - Willy Tarreau
# Use this script as a GCC prefix to build a source with uclibc.
# Note that it is smart enough to build kexec-tools and busybox.

compilo="$1" ; shift
# echo "uclibc: $@" >&2
if [ -z "$UCLIBCROOT" ]; then
  echo "UCLIBCROOT variable is not set. Please make it point to your uclibc sysroot."
  exit 1
fi
if [ ! -d "$UCLIBCROOT/." ]; then
  echo "UCLIBCROOT variable does not point to a valid directory. Please make it point to your uclibc sysroot."
  exit 1
fi

# Check if one parameter is '-c', '-E', '-M', '-r', or '-S'
args=" ${*} "
if [ "${args/ -c /}${args/ -E /}${args/ -S /}${args/ -M /}${args/ -r /}" \
  != "${args}${args}${args}${args}${args}" ]; then
  # we found at least one of '-c','-E','-S' or '-M'
  exec "$compilo" "$@" -isystem ${UCLIBCROOT}/usr/include
else
  # check if we need the exception handler
  libgcc_eh="$("$compilo" --print-file-name=libgcc_eh.a 2>/dev/null)"
  [ "${libgcc_eh##*/}" != "libgcc_eh.a" ] || libgcc_eh=
  # and if we need to include uclibc_nonshared.a (atexit, *unwind*, ...)
  uclibc_nonshared_a="${UCLIBCROOT}/usr/lib/uclibc_nonshared.a"
  [ -e "$uclibc_nonshared_a" ] || uclibc_nonshared_a=
  exec "$compilo" -nostdlib -static \
     -L${UCLIBCROOT}/usr/lib \
     -L${UCLIBCROOT}/lib \
     ${UCLIBCROOT}/usr/lib/crti.o \
     ${UCLIBCROOT}/usr/lib/crt1.o \
     ${UCLIBCROOT}/usr/lib/crtn.o \
     "$@" \
     -isystem ${UCLIBCROOT}/usr/include \
     ${UCLIBCROOT}/usr/lib/libc_pic.a \
     ${uclibc_nonshared_a} \
     -lgcc ${libgcc_eh##*/}
fi

