#!/bin/bash

# build-kernel-list - build a list of 2.6 kernels - version 0.0.12 - 2017-01-30
# This file is part of the Formilux project : http://formilux.ant-computing.com/
#
# Copyright (C) 2001-2017 Benoit Dolez & Willy Tarreau
#       mailto: benoit@ant-computing.com,willy@ant-computing.com
#
# This program is licenced under GPLv2 ( http://www.gnu.org/licenses/gpl.txt )

### TODO ###
# add options to bypass distclean, cp config, oldconfig, dep, bzimage, modules_install, ...

# This script builds kernels for all valid configurations passed on the command
# line. The configuration MUST be completely valid, and the script rejects those
# which are not (eg: new entries).
# If addons are found in the directory 'addons', they will be processed in the
# following order :
#   - execute addons/build.<$dir> 'clean' if <$dir> exists
#   - build kernel + modules
#   - execute addons/build.<$dir> 'compile'
#   - make kernel install
#   - execute addons/build.<$dir> 'install'
#
# It deduces every parameter from the configuration file name. It supports
# building several packages from a single file if the packages types are
# delimited with a '+'.
# Example :
#    # $0 confdir/config-2.6.27smp-wt4.rh73-boot-flx0+rh73.1-p4
#            |       |   | | |  |   |   |     |   |     |  |  |
#            |       |   | | |  |   |   |     |   |     |  |  +-> subarch (package)
#            |       |   | | |  |   |   |     |   |     |  +----> build number
#            |       |   | | |  |   |   |     |   |     +-------> second package
#            |       |   | | |  |   |   |     |   +-------------> first package
#            |       |   | | |  +---+---+-----+-----------------> extra version
#            |       |   | | +----------------------------------> sublevel
#            |       |   | +------------------------------------> minor
#            |       |   +--------------------------------------> major
#            |       +------------------------------------------> file type
#            +--------------------------------------------------> ignored

die() {
    ret=$1 ; shift
    echo "$@"
    exit $ret
}

usage() {
    echo "Formilux Linux Kernel packager - (C) 2004-2011 EXOSEC"
    echo "Usage:"
    echo "    ${0##*/} [ -h, --help ] [ -i,--install,--no-compile ]"
    echo "             [ -s, --suffix ] [ -r, --rerun ] [ -a arch ]"
    echo "             [ -m make ] [ -b bootimg ] [ -p platform ]"
    echo "             config_file..."
    echo
    echo "Output will be sent to \$OUTPUTDIR=$OUTPUTDIR"
    echo "Using: CROSS_COMPILE=$CROSS_COMPILE"
    echo "       CC=$CC USRCC=$USRCC HOSTCC=$HOSTCC PARALLELCC=$PARALLELCC"
    echo "       ARCH=$USERARCH DEFAULT_ARCH=$DEFAULT_ARCH KEEPDIR=$KEEPDIR"
    echo "       MAKE=$MAKE BOOTIMG=$BOOTIMG PLATFORM=$PLATFORM"
    echo "Note: this script needs sudo during the install phase."
    echo "CC may be used to force a command (eg: \"distcc gcc\")."
    echo "USRCC may be used to force a different CC to build init."
    echo "Use --suffix to automatically suffix the build version to the EXTRAVERSION."
    echo "x86_64 is used when the config's arch suffix is x86_64 or name contains smp64."
    echo "The config file can be omitted for rerun/install, or be set to \"flx\" for"
    echo "modules to be built and packaged for formilux ; default version will be used."
    echo "The preinit code will be picked from <platform> (may be an absolute path)."
    echo
    echo "Addons found : ${addons[@]}"
    echo
}

OUTPUTDIR=${OUTPUTDIR:-$PWD/KERNEL-PKG}
PARALLELDEP=${PARALLELDEP:-10}
PARALLELCC=${PARALLELCC:-6}
CC=${CC:-}
USRCC=${USRCC:-$CC}
HOSTCC=${HOSTCC:-gcc}
_SUDO=${_SUDO-sudo}
USERARCH=${ARCH}
DEFAULT_ARCH=${DEFAULT_ARCH:-i386}
_DEPMOD=${_DEPMOD:-depmod}
MAKE=${MAKE:-make}
BOOTIMG=${BOOTIMG:-bzImage}
PLATFORM=${PLATFORM:-}
KEEPDIR=${KEEPDIR:-}

mkdir -p $OUTPUTDIR || die 1 "Cannot create directory : $OUTPUTDIR"

# directory where this script is located
if [ -z "${0##*/*}" ]; then
  DIR="${0%/*}"
else
  DIR="$PWD"
fi

addons=( )
if [ -d "addons/." ]; then
  for i in $(cd addons && echo *); do
    if [ -d "addons/$i/." -a -e "addons/build.$i" ]; then
      chmod +x "addons/build.$i"
      addons[${#addons[@]}]="$i"
    fi
  done
fi

do_compile=1
do_suffix=0
do_rerun=0
while [ $# -gt 0 ]; do
    case "$1" in
    -a|--arch)
	USERARCH="$2"
	shift; shift
	;;
    -m|--make)
	MAKE="$2"
	shift; shift
	;;
    -b|--bootimg)
	BOOTIMG="$2"
	shift; shift
	;;
    -p|--platform)
	PLATFORM="$2"
	shift; shift
	;;
    -h|--help)
	usage
	exit 0
	;;
    -i|--no-compile|--install-only)
	do_compile=0
	shift
	;;
    -r|--rerun)
	do_rerun=1
	shift
	;;
    -s|--suffix)
	do_suffix=1
	shift
	;;
    *)
	break
	;;
    esac
done

if [ $# -eq 0 ]; then
    if [ $do_compile -eq 1 -a $do_rerun -eq 0 ]; then
        usage
        exit 1
    else
        # use an empty config name for compile-only or rerun
        echo "No config file specified, setting default build, no modules will be packaged."
        echo "You should use \"flx\" as a pseudo-config name to package for formilux."
        set -- ""
    fi
fi

# Find an efficient gzip implementation
if [ -z "$cmd_gzip" ]; then
  if [ "$(echo yes | (7za a -tgzip -mx9 -mpass=4 -si -so . | gzip -cd) 2>/dev/null)" = "yes" ]; then
    cmd_gzip="7za a -tgzip -mx9 -mpass=4 -si -so ."
  else
    cmd_gzip="gzip -c9"
  fi
fi

[ -e "Makefile" ] || die 1 "No Makefile found in current directory"

# appeared in 2.6.15
SRCVER="$(${MAKE} kernelversion 2>/dev/null)"
SRCMAJ=""
SRCMIN=""
SRCSUB=""
SRCEXT=""

# possible input formats : 3.10 3.10-rc7 3.10.15 3.10.15-rc1 2.6.32.8 2.6.32.8-rc1
SRCMAJ="${SRCVER%%.*}" ; SRCVER="${SRCVER#$SRCMAJ.}"
SRCMIN="${SRCVER%%.*}" ; SRCVER="${SRCVER#$SRCMIN}"
if [ -n "$SRCVER" -a -z "${SRCVER##.*}" ]; then
    SRCVER="${SRCVER#.}"
    SRCSUB="${SRCVER%%[^0-9]*}"
    SRCVER="${SRCVER#$SRCSUB}"
fi

SRCEXT="${SRCVER}"
SRCVER="${SRCMAJ}${SRCMIN:+.$SRCMIN}${SRCSUB:+.$SRCSUB}${SRCEXT:+$SRCEXT}"

echo "Source version: ${SRCVER:-unknown}"

tot_err=0
for cfg in "$@"; do
    # cfg = dir/config-2.4.27smp-wt4.rh73-flx0.1-p4
    # or "config-4.9.x-flx2.1-i586" for automatic versionning
    ver="${cfg##*/}"				# ver=config-2.4.27smp...
    ver="${ver#*-}"				# ver=2.4.27smp-wt4...
    major="${ver%%.*}" ; ver="${ver#$major.}"	# ver=4.27smp-wt4.rh73-flx0.1-p4
    minor="${ver%%.*}" ; ver="${ver#$minor}"	# ver=.27smp-wt4.rh73-flx0.1-p4
    if [ -n "$ver" -a -z "${ver##.*}" ]; then
        ver="${ver#.}"				# ver=27smp-wt4.rh73-flx0.1-p4
    fi
    sub="${ver%%-*}"				# sub=27smp
    if [ "$sub" != "x" ]; then
        sub="${sub%%[^0-9]*}"			# sub=27
    fi
    ver="${ver#$sub}"				# ver=smp-wt4.rh73-flx0.1-p4

    if [ -z "$cfg" ]; then
        cfg_auto=1
    elif [ "$cfg" = "flx" ]; then
        cfg="config-0.0.0-flx0.0-$USERARCH"
        cfg_auto=1
        major=0; minor=0; sub=0
    elif [ "$major.$minor.$sub" = "0.0.0" ]; then
        cfg_auto=0
        major=${SRCMAJ}; minor=${SRCMIN}; sub=${SRCSUB}; ver="${SRCEXT}${ver}"
    elif [ "$sub" = "x" ]; then
        cfg_auto=0
        sub=${SRCSUB}; ver="${SRCEXT}${ver}"
    else
        cfg_auto=0
    fi

    subarch="${ver##*-}"; ver="${ver%-$subarch}" # ver=smp-wt4.rh73-flx0.1
    build="${ver##*-}" ; extra="${ver%-$build}"	# extra=smp-wt4-rh73
    dist="${build%.*}" ; build=${build#$dist.}	# dist=flx0, build=1

    output="${major}.${minor}.${sub}${extra}${build:+.$build}${subarch:+-$subarch}"
    log="build-$output.log"
    rm -f $log

    if [ -n "$USERARCH" ]; then
        ARCH="$USERARCH"
    else
        if [ -z "$subarch" ]; then
            if [ -n "$extra" -a -z "${extra##*smp64*}" ]; then
                ARCH="x86_64"
            else
                ARCH="${DEFAULT_ARCH}"
            fi
        elif [ -z "${subarch##*x86_64}" ]; then
	    ARCH="x86_64"
        else
            ARCH="${DEFAULT_ARCH}"
        fi
    fi

    echo
    echo "##### building $cfg => $output #####"
    echo "DATE=$(date)"
    echo "CFG=$cfg"
    echo "MAJOR=$major"
    echo "MINOR=$minor"
    echo "SUB=$sub"
    echo "EXTRA=$extra"
    echo "DIST=$dist"
    echo "BUILD=$build"
    echo "ARCH=$ARCH"
    echo "SUBARCH=$subarch"
    echo "LOG=$log"
    echo

    if [ -n "${major##[0-9]*}" -o -n "${minor##[0-9]*}" ]; then
        echo "MAJOR or MINOR cannot contain non-digit characters."
	(( tot_err++ ))
	continue
    fi

    if [ $do_compile -eq 1 -a $do_rerun -eq 0 ] && [ -z "$subarch" -o -z "$dist" -o -z "$sub" -o -z "$minor" -o -z "$major" ]; then
	echo "Error! none of MAJOR, MINOR, SUB, DIST and ARCH can be empty"
	(( tot_err++ ))
	continue
    fi

    # The kernel version appearing in the package name can be a subset of
    # the full kernel version.

    KPKG="${major}.${minor}.${sub}${extra}"
    if [ "$do_suffix" = "1" ]; then
        extra="${extra}-${build}"
        KVER="${major}.${minor}.${sub}${extra}"
    else
        KVER="${major}.${minor}.${sub}${extra}"
    fi

    if [ $cfg_auto -eq 0 ]; then
        VERSTR=( VERSION="$major" PATCHLEVEL="$minor" SUBLEVEL="$sub" EXTRAVERSION="$extra" ARCH="$ARCH" CROSS_COMPILE="$CROSS_COMPILE" ${CC:+CC="${CC}"} HOSTCC="$HOSTCC" LOCALVERSION= CONFIG_LOCALVERSION_AUTO= CONFIG_LOCALVERSION= )
    else
        VERSTR=( ARCH="$ARCH" CROSS_COMPILE="$CROSS_COMPILE" ${CC:+CC="${CC}"} HOSTCC="$HOSTCC" LOCALVERSION= CONFIG_LOCALVERSION= )
    fi
    MAKE_CMD=( $MAKE "${VERSTR[@]}" )

    if [ $do_compile -eq 1 ]; then
        if [ $do_rerun -eq 0 ]; then
          echo "Doing make distclean..."
	  "${MAKE_CMD[@]}" distclean >/dev/null 2>&1
	  for addon in "${addons[@]}"; do
            echo "Cleaning addon '$addon'..."
	    addons/"build.$addon" clean "$KVER" "$PWD" "$PWD/addons/$addon"
          done
	  echo "Done."
	  rm -f .version .config
	  rm -f include/linux/version.h include/linux/modversions.h
	  cp $cfg .config

	  echo "Checking configuration file" | tee -a $OUTPUTDIR/$log
	  "${MAKE_CMD[@]}" oldconfig </dev/null >>$OUTPUTDIR/$log 2>&1 ; err=$?
	  if [ $err -ne 0 ]; then
	    echo "######### make oldconfig returned error code $err #########" | tee -a $OUTPUTDIR/$log
	    (( tot_err++ ))
	    continue
	  fi

	  #echo "Building dependencies" | tee -a $OUTPUTDIR/$log
	  #"${MAKE_CMD[@]}" -j $PARALLELDEP dep </dev/null >>$OUTPUTDIR/$log 2>&1; err=$?
	  #if [ $err -ne 0 ]; then
	  #  echo "######### make dep returned error code $err #########" | tee -a $OUTPUTDIR/$log
	  #  (( tot_err++ ))
	  #  continue
	  #fi
	fi

	echo "Building kernel and modules" | tee -a $OUTPUTDIR/$log
        rm -rf initramfs && mkdir initramfs
	"${MAKE_CMD[@]}" -j $PARALLELCC $BOOTIMG modules </dev/null >>$OUTPUTDIR/$log 2>&1; err=$?
	if [ $err -ne 0 ]; then
	    echo "######### make $BOOTIMG modules returned error code $err #########" | tee -a $OUTPUTDIR/$log
	    (( tot_err++ ))
	    continue
	fi

	# now build all addons
	addon_err=0
	for addon in "${addons[@]}"; do
          echo "Compiling addon '$addon'..."| tee -a $OUTPUTDIR/$log
	  addons/"build.$addon" compile "$KVER" "$PWD" "$PWD/addons/$addon" </dev/null >>$OUTPUTDIR/$log 2>&1
	  err=$?
	  if [ $err -ne 0 ]; then
	    addon_err=1
	    echo "######### compile of addon '$addon' returned error code $err #########" | tee -a $OUTPUTDIR/$log
	    (( tot_err++ ))
	  fi
        done
	echo "Done."

	if [ $addon_err -ne 0 ]; then
	  echo "######### errors encountered while compiling addons #########"
	  (( tot_err++ ))
	  continue
        fi
    else
	echo "Skipping compilation" | tee -a $OUTPUTDIR/$log
    fi

    # we can build several packages from one distro
    for curdist in ${dist//+/ }; do
	echo "##### packaging for $curdist #####"
	BUILDVERSION="${curdist}${build:+.$build}"
	destdir="$OUTPUTDIR/$output.${BUILDVERSION}"
	subarchdir="$destdir/$subarch"
	libmoddir="$subarchdir/lib/modules/$KVER"
	bootdir="$subarchdir/boot/$KVER"

	if [ "$destdir" == "/./" ]; then
	    echo "######### DANGER !!! ##########"
	    echo "# Something really bad happened ! destdir='$destdir'. Refusing to process further !"
	    echo "###############################"
	    exit 2
	fi

	$_SUDO rm -rf $destdir ; $_SUDO mkdir -p $subarchdir

	echo "Installing modules" >> $OUTPUTDIR/$log
	$_SUDO "${MAKE_CMD[@]}" INSTALL_MOD_PATH=$subarchdir \
	            INSTALL_MOD_STRIP="--strip-unneeded" \
	            DEPMOD="$_DEPMOD" \
	            modules_install </dev/null >> $OUTPUTDIR/$log 2>&1; err=$?
	if [ $err -ne 0 ]; then
	    echo "######### make modules_install returned error code $err #########" | tee -a $OUTPUTDIR/$log
	    [ -z "$KEEPDIR" ] && $_SUDO rm -rf $destdir
	    (( tot_err++ ))
	    continue
	fi

	if [ ! -d "$libmoddir" ]; then
	    if [ $cfg_auto -eq 0 ]; then
	        echo "##### WARNING: the output modules directory doesn't exist, probably because" | tee -a $OUTPUTDIR/$log
	        echo "##### CONFIG_LOCALVERSION_AUTO is set, trying to determine the proper name." | tee -a $OUTPUTDIR/$log
	    fi
	    dirs=( $(cd ${libmoddir%/*} && \ls -1d * ) )
	    if [ ${#dirs[@]} -eq 1 -a -d "${libmoddir%/*}/${dirs[0]}/kernel/." ]; then
	        KVER="${dirs[0]}"
	        libmoddir="$subarchdir/lib/modules/$KVER"
	        bootdir="$subarchdir/boot/$KVER"
	        echo "##### Now using $KVER as the kernel version." | tee -a $OUTPUTDIR/$log
	    fi
	fi

	if [ ! -d "$libmoddir" ]; then
	    echo "######### make modules_install failed to create $libmoddir #########" | tee -a $OUTPUTDIR/$log
	    echo "######### listing of ${libmoddir%/*} : #########" | tee -a $OUTPUTDIR/$log
	    ls -la ${libmoddir%/*} | tee -a $OUTPUTDIR/$log
	    [ -z "$KEEPDIR" ] && $_SUDO rm -rf $destdir
	    (( tot_err++ ))
	    continue
	fi

	# install all addons
	addon_err=0
	for addon in "${addons[@]}"; do
          echo "Installing addon '$addon'..."

	  $_SUDO addons/"build.$addon" install "$KVER" "$PWD" "$PWD/addons/$addon" "$subarchdir" </dev/null >>$OUTPUTDIR/$log 2>&1
	  err=$?
	  if [ $err -ne 0 ]; then
	    addon_err=1
	    echo "######### install of addon '$addon' returned error code $err #########" | tee -a $OUTPUTDIR/$log
	    (( tot_err++ ))
	  fi
        done
	echo "Done."

	if [ $addon_err -ne 0 ]; then
	  echo "######### errors encountered while installing addons #########"
	  [ -z "$KEEPDIR" ] && $_SUDO rm -rf $destdir
	  (( tot_err++ ))
	  continue
        fi

	# now that we have all the modules, let's generate the modules.dep file.
        [ -r System.map ] && $_SUDO $_DEPMOD -ae -F System.map -b "$subarchdir" -r "$KVER"

        # workaround for some new depmod from kmod building old kernels
	if [ -e "$libmoddir/modules.builtin.bin" -a ! -s "$libmoddir/modules.builtin.bin" ]; then
	  echo "Removing bogus empty modules.builtin.bin (please fix depmod, currently it is: \"$_DEPMOD\")."
	  $_SUDO rm -f "$libmoddir/modules.builtin.bin"
	fi

	curdir=$PWD
	case $curdist in
	flx*)
		#### UPDATE: the modules and files are now self-contained
		#### with the bzImage, so we do not need to package them again.
		#### The bzImage will be enough.

            # ensure we did not previously build an initramfs
            if [ -e initramfs/modules.tar -a -e usr/initramfs_data.o -a \
                 usr/initramfs_data.o -nt initramfs/modules.tar ]; then
                echo "Cleaning initramfs" >>$OUTPUTDIR/$log
                rm -rf initramfs && mkdir initramfs
                "${MAKE_CMD[@]}" -j $PARALLELCC $BOOTIMG CONFIG_INITRAMFS_SOURCE="" </dev/null >>$OUTPUTDIR/$log 2>&1; err=$?
            fi
            mkdir -p initramfs

	    # Compress all modules
            if [ -z "$DONT_GZIP_MODULES" ]; then
                echo "Compressing modules for kernel $version ..."
                du -s "${subarchdir}/lib/modules"
                find "${subarchdir}/lib/modules" -type f -name "*.ko"| while read; do
                    echo "Compressing module $REPLY -> $REPLY.gz"
                    $_SUDO sh -c "${CROSS_COMPILE}strip -S $REPLY && ${cmd_gzip} <$REPLY >$REPLY.gz 2>/dev/null && rm -f $REPLY"
                done >> $OUTPUTDIR/$log 2>&1
                du -s "${subarchdir}/lib/modules"
                echo "Done."
                [ -r System.map ] && $_SUDO $_DEPMOD -ae -F System.map -b "$subarchdir" -r "$KVER"

                # workaround for some new depmod from kmod building old kernels
                if [ -e "$libmoddir/modules.builtin.bin" -a ! -s "$libmoddir/modules.builtin.bin" ]; then
                    echo "Removing bogus empty modules.builtin.bin (please fix depmod, currently it is: \"$_DEPMOD\")."
                    $_SUDO rm -f "$libmoddir/modules.builtin.bin"
                fi
            fi
	    $_SUDO rm -f ${subarchdir}/lib/modules/${KVER}/build ${subarchdir}/lib/modules/${KVER}/source

            # save the modules right now for later use
            tar --owner=root --group=root --numeric-owner --mode=a+r,go-w -C "${subarchdir}/lib/modules" -cf - "${KVER}" > initramfs/modules.tar

	    $_SUDO mv $subarchdir/lib/modules $subarchdir/boot && $_SUDO rmdir $subarchdir/lib
	    # now everything is under $bootdir

	    $_SUDO chown -R root:adm $subarchdir/boot
	    $_SUDO chmod -R g-w,o-rwx $subarchdir/boot

            # install kernel
	    $_SUDO cp arch/${ARCH}/boot/$BOOTIMG .config System.map $bootdir >> $OUTPUTDIR/$log 2>&1; err=$?
	    if [ $err -ne 0 ]; then
		echo "######### cp $BOOTIMG .config System.map ... returned error code $err #########" | tee -a $OUTPUTDIR/$log
		[ -z "$KEEPDIR" ] && $_SUDO rm -rf $destdir
		(( tot_err++ ))
		continue
	    fi

	    $_SUDO ln -s $KVER/System.map $subarchdir/boot/System.map-$KVER
	    $_SUDO sh -c "$cmd_gzip <$bootdir/.config >$bootdir/.config.gz 2>/dev/null && rm -f $bootdir/.config"

	    $_SUDO chown -R root:adm $subarchdir/boot
	    $_SUDO chmod -R g-w,o-rwx $subarchdir/boot

	    # system.map is used by 'ps' to display the syscall being used (ps -o wchan)
	    $_SUDO chmod ugo+r $bootdir/System.map

	    # let's build the signature file
	    $_SUDO find $subarchdir/ -xdev -not -path $subarchdir/boot -printf "%P\n" | grep -v '^$' | \
		sh -c "( cd $subarchdir && $_SUDO xargs flx sign --ignore-dot --no-depth)" \
		>$OUTPUTDIR/kernel-${KPKG}-${BUILDVERSION}-$subarch.lst

	    # let's build the tar.gz
	    $_SUDO find $subarchdir/ -xdev -not -path $subarchdir/boot -printf "%P\n" | grep -v '^$' | \
		$_SUDO tar -C $subarchdir --no-recursion -T - -vcf - 2>>$OUTPUTDIR/$log | \
		${cmd_gzip} 2>/dev/null >$OUTPUTDIR/kernel-${KPKG}-${BUILDVERSION}-$subarch.tgz

	    cp .config $OUTPUTDIR/config-${KPKG}-${BUILDVERSION}-$subarch

            # We now have a complete kernel + modules packaged. We also want to have a
            # self-contained kernel image (allin1).

	    if [ -n "${PLATFORM}" -a -z "${PLATFORM##/*}" ]; then
		    tools26="${PLATFORM}"
	    else
		    tools26="$DIR/inst-mod26${PLATFORM:+-$PLATFORM}"
	    fi

            [ -d "$tools26/." ] || tools26="$DIR/inst-mod26"
            mkdir -p initramfs/{dev,proc,root}
            cp "${tools26}/.preinit" initramfs/
            if [ -s "${tools26}/init" ]; then
                    # init is pre-built, let's copy it
                    cp "${tools26}/init" initramfs/
            elif [ -s "${tools26}/init.c" -a -s "${tools26}/nolibc.h" ]; then
                    # init is not there but its sources are, so we can build
                    echo -n "Building initramfs/init from sources... "
                    ${USRCC:-"${CROSS_COMPILE}"gcc} -Os -nostdlib \
                       -include "${tools26}/nolibc.h" -s -Wl,--gc-sections \
                       -fno-exceptions -fno-asynchronous-unwind-tables \
                       -fno-unwind-tables -fno-ident -fomit-frame-pointer \
                       -o initramfs/init "${tools26}/init.c" -lgcc
                    ${CROSS_COMPILE}strip -x --strip-unneeded \
                       -R .gnu.attributes -R .mdebug.abi32 \
                       -R .note -R .note.ABI-tag initramfs/init
                    echo "done."
            fi

            if [ ! -s initramfs/init ]; then
                    echo "WARNING! no init found for initramfs!"
            fi

            if [ -e "${tools26}/busybox" ]; then cp "${tools26}/busybox" initramfs/; fi

            echo "Building initramfs for all-in-one kernel" >>$OUTPUTDIR/$log
            "${MAKE_CMD[@]}" -j $PARALLELCC $BOOTIMG CONFIG_INITRAMFS_SOURCE=$PWD/initramfs </dev/null >>$OUTPUTDIR/$log 2>&1; err=$?

            echo "Packaging all-in-one kernel" >>$OUTPUTDIR/$log
	    $_SUDO cp arch/${ARCH}/boot/$BOOTIMG .config System.map $bootdir >> $OUTPUTDIR/$log 2>&1; err=$?
	    if [ $err -ne 0 ]; then
		echo "######### cp $BOOTIMG .config System.map ... returned error code $err #########" | tee -a $OUTPUTDIR/$log
		[ -z "$KEEPDIR" ] && $_SUDO rm -rf $destdir
		(( tot_err++ ))
		continue
	    fi

	    # let's build the signature file
	    $_SUDO find $subarchdir/ -xdev \( -name $BOOTIMG -o -name .config -o -name System.map \) -printf "%P\n" | \
		sh -c "( cd $subarchdir && $_SUDO xargs flx sign --ignore-dot --no-depth)" \
		>$OUTPUTDIR/kernel-${KPKG}-${BUILDVERSION}-allin1-$subarch.lst

	    # let's build the tar.gz
	    $_SUDO find $subarchdir/ -xdev \( -name $BOOTIMG -o -name .config -o -name System.map \) -printf "%P\n" | \
		$_SUDO tar -C $subarchdir --no-recursion -T - -vcf - 2>>$OUTPUTDIR/$log | \
		${cmd_gzip} 2>/dev/null >$OUTPUTDIR/kernel-${KPKG}-${BUILDVERSION}-allin1-$subarch.tgz

            # not needed since we already have one
	    # cp .config $OUTPUTDIR/config-${KPKG}-${BUILDVERSION}-allin1-$subarch
	    ;;
	rh*)
	    $_SUDO mkdir -p $subarchdir/boot
	    $_SUDO cp arch/${ARCH}/boot/$BOOTIMG $subarchdir/boot/vmlinuz-$KVER >> $OUTPUTDIR/$log 2>&1 && \
	        $_SUDO cp .config $subarchdir/boot/config-$KVER >> $OUTPUTDIR/$log 2>&1 && \
	        $_SUDO cp System.map $subarchdir/boot/System.map-$KVER >> $OUTPUTDIR/$log 2>&1; err=$?
	    if [ $err -ne 0 ]; then
		echo "######### cp $BOOTIMG .config System.map ... returned error code $err #########" | tee -a $OUTPUTDIR/$log
		[ -z "$KEEPDIR" ] && $_SUDO rm -rf $destdir
		(( tot_err++ ))
		continue
	    fi
	    $_SUDO rm -f $subarchdir/boot/build

	    for i in $($_SUDO find $libmoddir -type f -name '*.o'); do
		echo "Stripping $i"
		$_SUDO ${CROSS_COMPILE}strip -S $i
	    done >> $OUTPUTDIR/$log 2>&1


	    $_SUDO chown -R root:adm $subarchdir/{boot,lib}
	    $_SUDO chmod -R g-w,o-rwx $subarchdir/{boot,lib}
	    # system.map is used by 'ps' to display the syscall being used (ps -o wchan)
	    $_SUDO chmod ugo+r $subarchdir/boot/System.map-${KVER}

	    # let's build the tar.gz
	    $_SUDO find $subarchdir -xdev -not -path $subarchdir/boot -not -path $subarchdir/lib \
		-not -path $subarchdir/lib/modules -printf "%P\n" | \
		grep -v '^$' | $_SUDO tar -C $subarchdir --no-recursion -T - -vcf - 2>>$OUTPUTDIR/$log | \
		gzip -c9 >$OUTPUTDIR/kernel-${KPKG}-${BUILDVERSION}-$subarch.tgz

	    cp .config $OUTPUTDIR/config-$KPKG-$BUILDVERSION-$subarch
	    ;;
	*)
	    echo "######## unknown packaging method for distribution $curdist #######" | tee -a $OUTPUTDIR/$log
	    (( tot_err++ ))
	    ;;
	esac ## case $curdist

	[ -z "$KEEPDIR" ] && $_SUDO rm -rf $destdir
	echo "#### package done ! ####" >> $OUTPUTDIR/$log
    done
done

echo
date
echo "Done !"

# report any error we've encountered
exit $tot_err
